# Generated by Django 3.1.4 on 2021-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('number_tel', models.CharField(max_length=10, verbose_name='Número Telefónico')),
                ('area', models.CharField(max_length=50, verbose_name='Área')),
                ('school', models.CharField(max_length=100, verbose_name='Escuela de procedencia')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Fecha de registro')),
                ('active', models.BooleanField(default=False, verbose_name='Alumno Activo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'unique_together': {('email', 'number_tel')},
            },
        ),
    ]
